
name: Run Tests

on: push

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: 22.3.2
        elixir-version: 1.10.2

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
      env:
        MIX_ENV: test
        DATABASE_URL: not-good
        SECRET_KEY_BASE: not-secret

    - name: Get the repo
      id: get_repo
      run: echo ::set-output name=NAME::${GITHUB_REPOSITORY/*\//}

    - name: Get the reference
      id: get_ref
      run: echo ::set-output name=REF::${GITHUB_REF/refs\/heads\//}

    - name: Run Credo
      run: mix credo --strict
      env:
        MIX_ENV: test
